### ISSUE TITLE
Create CI/CD workflows

### ISSUE THREAD

**Issue by thepetk** [pygreece/python-docs-gr#5]
Create github workflows that will check & test the project for every new PR or push to the main branch.

**Comment by egeakman** [comment]
Hey hey! We use (this)[https://github.com/python/python-docs-tr/blob/3.12/.github/workflows/build.yml] workflow for checking PRs and pushes in the Turkish translation.

**Comment by egeakman** [comment]
Oh, and running pre-commit checks might be useful:

pre-commit config:
```yaml
ci:
  autofix_prs: false
  autoupdate_branch: "pre-commit-autoupdate"
  autoupdate_schedule: weekly

repos:
  - repo: local
    hooks:
      - id: style-print
        name: ""
        entry: "style-print 'Please report any issues at: https://github.com/python/python-docs-tr/issues' 'rUBI{y}'"
        language: python
        additional_dependencies: ["style-print"]
        pass_filenames: false
        verbose: true

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
```

GHA workflow:
```yaml
name: pre-commit-ci
on: [push, pull_request, workflow_dispatch]

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit tools
        uses: actions/cache@v4
        with:
          key: pre-commit-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run pre-commit-ci-lite
        uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
```
