### ISSUE TITLE
Integrate with Read the Docs

### ISSUE THREAD

**Issue by thepetk** [pygreece/python-docs-gr#6]
A nice feature would be to make an integration between the github repo here and readthedocs.io

**Comment by egeakman** [comment]
Here is the configuration file we use! It builds the HTML pages and serve them from the ``_readthedocs/html/`` directory.

```yaml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3"

  apt_packages:
    - make
    - gettext

  commands:
    - git clone https://github.com/python/cpython.git venv/cpython/
    - python -m pip install -r venv/cpython/Doc/requirements.txt
    - make
    - mkdir -p _readthedocs/html/
    - cp -r venv/cpython/Doc/build/html/* _readthedocs/html/
```
